class categor{
  static  List<Caegory> Items = [

  ];
}


class Autogenerated {
  List<Caegory>? caegory;

  Autogenerated({this.caegory});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['Caegory'] != null) {
      caegory = <Caegory>[];
      json['Caegory'].forEach((v) {
        caegory!.add(new Caegory.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.caegory != null) {
      data['Caegory'] = this.caegory!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Caegory {
  int? id;
  String? name;
  String? description;
  String? iconUrl;
  String? iconName;

  Caegory({this.id, this.name, this.description, this.iconUrl, this.iconName});

  Caegory.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    iconUrl = json['icon_url'];
    iconName = json['icon_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['description'] = this.description;
    data['icon_url'] = this.iconUrl;
    data['icon_name'] = this.iconName;
    return data;
  }
}