class Regions{
  static  List<CountryRegion> Items = [

  ];
}

class Autogenerated {
  List<CountryRegion>? countryRegion;

  Autogenerated({this.countryRegion});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['countryRegion'] != null) {
      countryRegion = <CountryRegion>[];
      json['countryRegion'].forEach((v) {
        countryRegion!.add(new CountryRegion.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.countryRegion != null) {
      data['countryRegion'] =
          this.countryRegion!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class CountryRegion {
  int? id;
  String? name;

  CountryRegion({this.id, this.name});

  CountryRegion.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}