import 'dart:core';
import 'dart:core';

import 'package:errandia/modal/Region.dart';
import 'package:errandia/modal/Town.dart';
import 'package:errandia/modal/category.dart';

class Shop {
  final int id;
  final String name;
  final String? description;
  final String? image;
  final Category? category;
  final String? slogan;
  final String? address;
  final String? phone;
  final String? street;
  final CountryRegion? region;
  final Town? town;
  final String? website;
  final String? facebook;
  final String? instagram;
  final String? twitter;
  final String? whatsapp;

  Shop({required this.id, required this.name, this.description, this.image,
    this.category, this.slogan, this.address, this.phone, this.street, this.region, this.town,
    this.website, this.facebook, this.instagram, this.twitter, this.whatsapp});

  factory Shop.fromJson(Map<String, dynamic> json) {
    return Shop(
      id: json['id'],
      name: json['name'],
      description: json['description'],
      image: json['image'],
      category: json['category'] != null ? Category.fromJson(json['category']) : null,
      slogan: json['slogan'],
      address: json['address'],
      phone: json['phone'],
      street: json['street'],
      region: json['region'] != null ? CountryRegion.fromJson(json['region']) : null,
      town: json['town'] != null ? Town.fromJson(json['town']) : null,
      website: json['website'],
      facebook: json['facebook'],
      instagram: json['instagram'],
      twitter: json['twitter'],
      whatsapp: json['whatsapp'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['description'] = this.description;
    data['image'] = this.image;
    if (this.category != null) {
      data['category'] = this.category!.toJson();
    }
    data['slogan'] = this.slogan;
    data['address'] = this.address;
    data['phone'] = this.phone;
    data['street'] = this.street;
    if (this.region != null) {
      data['region'] = this.region!.toJson();
    }
    if (this.town != null) {
      data['town'] = this.town!.toJson();
    }
    data['website'] = this.website;
    data['facebook'] = this.facebook;
    data['instagram'] = this.instagram;
    data['twitter'] = this.twitter;
    data['whatsapp'] = this.whatsapp;
    return data;
  }
}

class Shops {
  static List<Shop> Items = [];
}

class Autogenerated {
  List<Shop>? shop;

  Autogenerated({this.shop});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['Shop'] != null) {
      shop = <Shop>[];
      json['Shop'].forEach((v) {
        shop!.add(new Shop.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.shop != null) {
      data['Shop'] = this.shop!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}