
class plans {
  static List<SubscriptionPlan> Items = [

  ];
}

class AutoGenerated {
  List<SubscriptionPlan>? plans;

  AutoGenerated({this.plans});

  AutoGenerated.fromJson(Map<String, dynamic> json) {
    if (json['plans'] != null) {
      plans = <SubscriptionPlan>[];
      json['plans'].forEach((v) {
        plans!.add(SubscriptionPlan.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (plans != null) {
      data['plans'] = plans!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SubscriptionPlan {
  int? id;
  String? name;
  String? description;
  String? unitPrice;

  SubscriptionPlan({this.id, this.name, this.description, this.unitPrice});

  SubscriptionPlan.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    unitPrice = json['unit_price'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['unit_price'] = unitPrice;
    return data;
  }
}