class Towns{
  static  List<Town> Items = [

  ];
}

class Autogenerated {
  List<Town>? town;

  Autogenerated({this.town});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['Town'] != null) {
      town = <Town>[];
      json['Town'].forEach((v) {
        town!.add(new Town.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.town != null) {
      data['Town'] = this.town!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Town {
  int? id;
  String? name;

  Town({this.id, this.name});

  Town.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}